/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search cities worldwide - Geocoding autocomplete with coordinates and timezone
         * @description City autocomplete and geocoding search across 7,000+ locations in 227 countries. Returns geographic coordinates (latitude, longitude), IANA timezone, and DST-aware UTC offset for each match. Built for birth chart location pickers, horoscope apps, event scheduling, and any feature requiring place-to-coordinates resolution. Partial name matching with intelligent ranking: exact prefix matches first, then sorted by population for relevance. Covers all major cities in Europe, Americas, Asia, Africa, and Oceania.
         */
        get: operations["searchCities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all 227 countries - ISO codes and city coverage
         * @description Returns all 227 countries with ISO 3166-1 alpha-2 and alpha-3 codes, plus the number of searchable cities per country. Use this endpoint to build country dropdown menus, regional filters, or to check city coverage before querying. Sorted alphabetically by country name. Covers Europe, Americas, Asia, Middle East, Africa, and Oceania.
         */
        get: operations["listCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries/{iso2}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get cities in a country - Geocoding directory sorted by population
         * @description Returns all cities for a specific country, identified by ISO 3166-1 alpha-2 code (e.g. DE for Germany, FR for France, GB for United Kingdom, US for United States). Each city includes geographic coordinates, IANA timezone, and DST-aware UTC offset for direct use in astrology birth chart, horoscope, transit, and panchang calculations. Cities sorted by population with the largest metropolitan areas first.
         */
        get: operations["getCitiesByCountry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    searchCities: {
        parameters: {
            query: {
                /** @description City name to search for. Matches against city name, province/state, or combined "city country" queries. Case-insensitive with partial matching (e.g. "ber" matches Berlin, Bern, Bergen). */
                q: string;
                /** @description Maximum number of results to return (1-50). Defaults to 10. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching cities sorted by relevance (prefix match first) then population */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description City name as commonly used. Matches the local or internationally recognized name for the location.
                         * @example Berlin
                         */
                        city: string;
                        /**
                         * @description State, province, canton, or administrative region. Helps disambiguate cities with the same name across regions (e.g. Springfield IL vs Springfield MO).
                         * @example Berlin
                         */
                        province: string;
                        /**
                         * @description Full country name in English.
                         * @example Germany
                         */
                        country: string;
                        /**
                         * @description ISO 3166-1 alpha-2 country code. Use for filtering cities by country or building country-specific location pickers.
                         * @example DE
                         */
                        iso2: string;
                        /**
                         * @description Geographic latitude in decimal degrees (-90 to 90). Pass directly to birth chart, natal chart, horoscope, synastry, transit, kundli, and panchang API endpoints as the latitude parameter.
                         * @example 52.52
                         */
                        latitude: number;
                        /**
                         * @description Geographic longitude in decimal degrees (-180 to 180). Pass directly to astrology, horoscope, and panchang API endpoints alongside latitude.
                         * @example 13.405
                         */
                        longitude: number;
                        /**
                         * @description IANA timezone identifier following the tz database standard (e.g. Europe/Berlin, America/New_York, Asia/Tokyo). Use with JavaScript Date, Luxon, day.js, or any date library for accurate local time conversion.
                         * @example Europe/Berlin
                         */
                        timezone: string;
                        /**
                         * @description Current UTC offset in decimal hours, automatically adjusted for daylight saving time. Pass directly as the timezone parameter in astrology API endpoints. Examples: 1 for CET, 2 for CEST, -5 for EST, 5.5 for IST, 5.75 for Nepal.
                         * @example 1
                         */
                        utcOffset: number;
                        /**
                         * @description City population estimate from geographic databases. Larger cities rank higher in search results, ensuring major metropolitan areas appear first in autocomplete suggestions.
                         * @example 3644826
                         */
                        population: number;
                    }[];
                };
            };
        };
    };
    listCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted list of all 227 countries with ISO codes and city counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Full country name in English. Use for display in location pickers and dropdown menus.
                         * @example Germany
                         */
                        name: string;
                        /**
                         * @description ISO 3166-1 alpha-2 country code. Use as the identifier when fetching cities for a specific country via the /countries/{iso2} endpoint.
                         * @example DE
                         */
                        iso2: string;
                        /**
                         * @description ISO 3166-1 alpha-3 country code. Three-letter standard used in international data exchange.
                         * @example DEU
                         */
                        iso3: string;
                        /**
                         * @description Number of searchable cities available for this country. Useful for showing coverage in UI or deciding whether to offer city search for a given country.
                         * @example 82
                         */
                        cityCount: number;
                    }[];
                };
            };
        };
    };
    getCitiesByCountry: {
        parameters: {
            query?: {
                /** @description Maximum number of cities to return (1-200). Defaults to 50. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description ISO 3166-1 alpha-2 country code, case-insensitive. Common codes: DE (Germany), FR (France), GB (United Kingdom), US (United States), ES (Spain), IT (Italy), NL (Netherlands), IN (India), BR (Brazil), JP (Japan). */
                iso2: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cities in the specified country, sorted by population (largest first) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description City name as commonly used. Matches the local or internationally recognized name for the location.
                         * @example Berlin
                         */
                        city: string;
                        /**
                         * @description State, province, canton, or administrative region. Helps disambiguate cities with the same name across regions (e.g. Springfield IL vs Springfield MO).
                         * @example Berlin
                         */
                        province: string;
                        /**
                         * @description Full country name in English.
                         * @example Germany
                         */
                        country: string;
                        /**
                         * @description ISO 3166-1 alpha-2 country code. Use for filtering cities by country or building country-specific location pickers.
                         * @example DE
                         */
                        iso2: string;
                        /**
                         * @description Geographic latitude in decimal degrees (-90 to 90). Pass directly to birth chart, natal chart, horoscope, synastry, transit, kundli, and panchang API endpoints as the latitude parameter.
                         * @example 52.52
                         */
                        latitude: number;
                        /**
                         * @description Geographic longitude in decimal degrees (-180 to 180). Pass directly to astrology, horoscope, and panchang API endpoints alongside latitude.
                         * @example 13.405
                         */
                        longitude: number;
                        /**
                         * @description IANA timezone identifier following the tz database standard (e.g. Europe/Berlin, America/New_York, Asia/Tokyo). Use with JavaScript Date, Luxon, day.js, or any date library for accurate local time conversion.
                         * @example Europe/Berlin
                         */
                        timezone: string;
                        /**
                         * @description Current UTC offset in decimal hours, automatically adjusted for daylight saving time. Pass directly as the timezone parameter in astrology API endpoints. Examples: 1 for CET, 2 for CEST, -5 for EST, 5.5 for IST, 5.75 for Nepal.
                         * @example 1
                         */
                        utcOffset: number;
                        /**
                         * @description City population estimate from geographic databases. Larger cities rank higher in search results, ensuring major metropolitan areas appear first in autocomplete suggestions.
                         * @example 3644826
                         */
                        population: number;
                    }[];
                };
            };
        };
    };
}
